---
# cnx-transforms
language: python
python:
  - "3.4"
before_install:
  # Install cnx-epub
  - git clone https://github.com/Connexions/cnx-epub.git
  - cd cnx-epub && sudo python setup.py install && cd ..
  # Scripts get installed to /usr/local/bin
  - pip install coverage
  - pip install coveralls
install:
  - python setup.py install 
script:
  - coverage run --source=cnxtransforms setup.py test
after_success:
  - coveralls
notifications:
  email: false
